/** Análise de documento (/fila/:id). */
export const analisePage = {
  voltar: 'Voltar para a fila',
  naoEncontradoTitle: 'Este envio não está mais na fila',
  naoEncontradoDescription: 'O documento pode ter sido analisado por outra pessoa ou o endereço está incorreto. Volte para a fila e escolha outro item.',
  naoEncontradoAction: 'Voltar para a fila',
  viewer: {
    paginaAnterior: 'Página anterior',
    proximaPagina: 'Próxima página',
    pagina: (atual: number, total: number) => `Página ${atual} de ${total}`,
    diminuirZoom: 'Diminuir zoom',
    aumentarZoom: 'Aumentar zoom',
    zoom: (pct: number) => `${pct}%`,
    baixar: 'Baixar',
    baixado: (arquivo: string) => `Download iniciado: ${arquivo}`,
    previewLabel: (documento: string) => `Pré-visualização de ${documento}`,
    secao: '1. Escopo e responsabilidades',
    tabela: ['Item', 'Situação', 'Observação'],
    rodape: (data: string, pagina: number, total: number) => `Enviado em ${data} • página ${pagina} de ${total}`,
  },
  dados: {
    title: 'Dados do envio',
    fornecedor: 'Fornecedor',
    lista: 'Lista',
    exigidoEm: 'Exigido em',
    documento: 'Documento',
    tipo: 'Tipo',
    enviadoEm: 'Enviado em',
    espera: 'Espera',
    validadeInformada: 'Validade informada',
    semValidade: 'Sem validade',
    renovacao: 'Envio',
    renovacaoTexto: 'Nova versão — a atual continua valendo até a decisão',
  },
  anteriores: {
    title: 'Envios anteriores',
    vazio: 'Primeiro envio deste documento.',
    versaoAtual: 'versão em vigor',
  },
  decisao: {
    title: 'Decisão',
    validade: 'Validade do documento',
    validadePlaceholder: 'dd/mm/aaaa',
    validadeHint: 'Preenchida com a data informada pelo fornecedor. Corrija se estiver diferente no documento.',
    validadeErro: 'Informe uma data futura no formato dd/mm/aaaa.',
    semValidade: 'Este documento não tem validade. Ao aprovar, ele vale até ser substituído.',
    reprovar: 'Reprovar',
    aprovar: 'Aprovar documento',
    limpar: 'Limpar',
  },
  reprovacao: {
    title: 'Reprovar documento',
    motivo: 'Motivo da reprovação',
    observacao: 'Observação para o fornecedor',
    observacaoPlaceholder: 'Escreva o que precisa ser corrigido no reenvio.',
    observacaoHint: 'O fornecedor lê este texto no portal e por e-mail.',
    observacaoErro: 'Explique ao fornecedor o que corrigir.',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar reprovação',
    limpar: 'Limpar',
  },
  decidido: {
    title: 'Decisão registrada',
    aprovado: (quem: string, hora: string) => `Aprovado por ${quem} às ${hora}.`,
    reprovado: (quem: string, hora: string) => `Reprovado por ${quem} às ${hora}.`,
    validoAte: (data: string) => `Vale até ${data}.`,
    semValidade: 'Vale até ser substituído.',
    motivo: (motivo: string) => `Motivo: ${motivo}.`,
    proximo: 'Próximo da fila',
    voltar: 'Voltar para a fila',
    filaVazia: 'Não há mais nada na fila.',
  },
  modalAprovar: {
    title: 'Aprovar documento',
    comValidade: (documento: string, data: string, aviso: number) =>
      `${documento} fica válido até ${data}. O sistema avisa a equipe e o fornecedor ${aviso} dias antes do vencimento.`,
    semValidade: (documento: string) => `${documento} fica aprovado sem data de validade e vale para todas as obras que o exigem.`,
    renovacao: 'A versão anterior deixa de valer e passa para o histórico de envios.',
    voltar: 'Voltar',
    confirmar: 'Aprovar documento',
    toast: 'Documento aprovado e fornecedor avisado',
  },
  modalReprovar: {
    title: 'Confirmar reprovação',
    description: 'O fornecedor recebe o motivo e a sua observação por e-mail e pode reenviar o documento corrigido.',
    alerta: 'O documento volta para a lista de pendências do fornecedor.',
    alertaRenovacao: 'A versão atual continua valendo até o vencimento; só a nova versão é recusada.',
    voltar: 'Voltar',
    confirmar: 'Confirmar reprovação',
    toast: 'Documento reprovado e fornecedor avisado',
  },
} as const;
