/** Análise de documento (/fila/:id) — também usada em modo leitura. */
export const analisePage = {
  naoEncontradoTitle: 'Documento não encontrado',
  naoEncontradoDescription: 'O endereço pode estar incorreto. Volte e escolha outro documento.',
  naoEncontradoAction: 'Voltar',
  navegacao: {
    posicao: (atual: number, total: number) => `${atual} de ${total}`,
    posicaoLabel: (atual: number, total: number) => `Documento ${atual} de ${total}`,
    anterior: 'Documento anterior',
    proximo: 'Próximo documento',
    dica: 'Use as setas ← e → do teclado para passar de um documento ao outro.',
    origemFila: 'Fila de análise',
  },
  viewer: {
    paginaAnterior: 'Página anterior',
    proximaPagina: 'Próxima página',
    pagina: (atual: number, total: number) => `Página ${atual} de ${total}`,
    diminuirZoom: 'Diminuir zoom',
    aumentarZoom: 'Aumentar zoom',
    zoom: (pct: number) => `${pct}%`,
    baixar: 'Baixar',
    baixado: (arquivo: string) => `Download iniciado: ${arquivo}`,
    previewLabel: (documento: string) => `Pré-visualização de ${documento}`,
    secao: '1. Escopo e responsabilidades',
    tabela: ['Item', 'Situação', 'Observação'],
    rodape: (data: string, pagina: number, total: number) => `Enviado em ${data} • página ${pagina} de ${total}`,
  },
  dados: {
    title: 'Dados do envio',
    fornecedor: 'Fornecedor',
    lista: 'Lista',
    exigidoEm: 'Exigido em',
    documento: 'Documento',
    tipo: 'Tipo',
    enviadoEm: 'Enviado em',
    espera: 'Espera',
    validadeInformada: 'Validade informada',
    validade: 'Validade',
    semValidade: 'Sem validade',
    renovacao: 'Envio',
    renovacaoTexto: 'Nova versão — a atual continua valendo até a decisão',
  },
  anteriores: {
    title: 'Envios anteriores',
    vazio: 'Primeiro envio deste documento.',
    versaoAtual: 'versão em vigor',
  },
  decisao: {
    title: 'Decisão',
    validade: 'Validade do documento',
    validadePlaceholder: 'dd/mm/aaaa',
    validadeHint: 'Preenchida com a data informada pelo fornecedor. Corrija se estiver diferente no documento.',
    validadeErro: 'Informe uma data futura no formato dd/mm/aaaa.',
    semValidade: 'Este documento não tem validade. Ao aprovar, ele vale até ser substituído.',
    reprovar: 'Reprovar',
    aprovar: 'Aprovar documento',
    limpar: 'Limpar',
  },
  reprovacao: {
    title: 'Reprovar documento',
    motivo: 'Motivo da reprovação',
    observacao: 'Observação para o fornecedor',
    observacaoPlaceholder: 'Escreva o que precisa ser corrigido no reenvio.',
    observacaoHint: 'O fornecedor lê este texto no portal e por e-mail.',
    observacaoErro: 'Explique ao fornecedor o que corrigir.',
    cancelar: 'Cancelar',
    confirmar: 'Confirmar reprovação',
    limpar: 'Limpar',
  },
  leitura: {
    title: 'Decisão registrada',
    aprovado: (quem: string, data: string, hora: string) => `Aprovado por ${quem} em ${data}, às ${hora}.`,
    reprovado: (quem: string, data: string, hora: string) => `Reprovado por ${quem} em ${data}, às ${hora}.`,
    motivo: 'Motivo',
    observacao: 'Observação ao fornecedor',
    validoAte: (data: string) => `Vale até ${data}.`,
    venceu: (data: string) => `Venceu em ${data}. O documento continua pendente até o fornecedor enviar outro.`,
    semValidade: 'Vale até ser substituído.',
    semRegistro: 'Não há registro de quem decidiu.',
    leituraNota: 'Modo leitura: este documento já foi decidido. Uma nova versão enviada pelo fornecedor volta para a fila.',
  },
  modalAprovar: {
    title: 'Aprovar documento',
    comValidade: (documento: string, data: string, aviso: number) =>
      `${documento} fica válido até ${data}. O sistema avisa a equipe e o fornecedor ${aviso} dias antes do vencimento.`,
    semValidade: (documento: string) => `${documento} fica aprovado sem data de validade e vale para todas as obras que o exigem.`,
    renovacao: 'A versão anterior deixa de valer e passa para o histórico de envios.',
    voltar: 'Voltar',
    confirmar: 'Aprovar documento',
    toast: 'Documento aprovado e fornecedor avisado.',
  },
  modalReprovar: {
    title: 'Confirmar reprovação',
    description: 'O fornecedor recebe o motivo e a sua observação por e-mail e pode reenviar o documento corrigido.',
    alerta: 'O documento volta para a lista de pendências do fornecedor.',
    alertaRenovacao: 'A versão atual continua valendo até o vencimento; só a nova versão é recusada.',
    voltar: 'Voltar',
    confirmar: 'Confirmar reprovação',
    toast: 'Documento reprovado e fornecedor avisado.',
  },
  /** Depois da decisão: avança para o próximo pendente da mesma origem, ou volta quando acaba. */
  avanco: {
    proximo: (decisao: string) => `${decisao} Abrindo o próximo pendente.`,
    fimFila: (decisao: string) => `${decisao} A fila terminou: não há mais nada esperando análise.`,
    fimFornecedor: (decisao: string) => `${decisao} Não há mais documentos deste fornecedor esperando análise.`,
    fimObra: (decisao: string) => `${decisao} Não há mais documentos desta obra esperando análise.`,
  },
} as const;
