/** Página de amostra do design system (só em desenvolvimento). */
export const componentesPage = {
  title: 'Componentes base',
  subtitle: 'Amostra do design system com todos os estados: normal, hover, foco e desabilitado.',
  sections: {
    buttons: 'Botões',
    badges: 'Badges e tags',
    forms: 'Campos de formulário',
    filters: 'Busca, filtros e abas',
    metrics: 'Faixa de métricas',
    blocks: 'Cartões e blocos',
    table: 'Tabela',
    overlays: 'Drawer, modal e toast',
    feedback: 'Notas e alertas',
    states: 'Estados de página',
  },
  buttons: {
    primary: 'Aprovar documento',
    secondary: 'Reprovar',
    tertiary: 'Cancelar',
    link: 'Ver fila completa',
    add: 'Vincular fornecedor',
    sm: 'Analisar',
    disabled: 'Desabilitado',
    back: 'Voltar para a fila',
    close: 'Fechar',
    download: 'Baixar arquivo',
    sizesNote: 'md 40px · sm 32px · no celular, todo alvo tem pelo menos 44px.',
  },
  forms: {
    validity: 'Validade do documento',
    validityPlaceholder: 'dd/mm/aaaa',
    validityHint: 'O sistema avisa 30 dias antes do vencimento.',
    cnpj: 'CNPJ',
    cnpjValue: '12.345.678/0001-90',
    cnpjError: 'Este CNPJ já está cadastrado: Construtora Exemplo Ltda.',
    disabled: 'Código da obra',
    disabledValue: 'OB-2401',
    reason: 'Motivo da reprovação',
    reasons: [
      { value: 'ilegivel', label: 'Documento ilegível' },
      { value: 'validade', label: 'Fora da validade' },
      { value: 'incorreto', label: 'Documento incorreto' },
      { value: 'assinatura', label: 'Falta assinatura' },
    ],
    note: 'Observação para o fornecedor',
    notePlaceholder: 'Escreva o que precisa ser corrigido no reenvio.',
    noteHint: 'O fornecedor lê este texto no portal e por e-mail.',
    checkboxes: {
      checked: 'Residencial Mirante do Parque',
      unchecked: 'Reserva das Águas',
      locked: 'Edifício Jardins da Torre',
      lockedHint: 'Já vinculada',
      disabled: 'Centro Clínico Boa Viagem',
      disabledHint: 'Obra concluída',
    },
  },
  filters: {
    searchLabel: 'Buscar na fila',
    searchPlaceholder: 'Buscar por fornecedor, obra ou documento',
    groupLabel: 'Filtrar fila',
    options: [
      { value: 'todos', label: 'Todos', count: 12 },
      { value: 'documentos', label: 'Documentos', count: 9 },
      { value: 'funcionario', label: 'Documentos de funcionário', count: 3 },
      { value: 'urgentes', label: 'Urgentes', count: 3 },
    ],
    selectSm: [
      { value: 'todos', label: 'Todos os tipos' },
      { value: 'servico', label: 'Serviço 26' },
      { value: 'material', label: 'Material 15' },
    ],
    selectSmLabel: 'Tipo de fornecedor',
    tabsLabel: 'Seções da ficha',
    tabs: [
      { value: 'docs', label: 'Documentos' },
      { value: 'exigencias', label: 'Exigências' },
      { value: 'obras', label: 'Obras' },
      { value: 'historico', label: 'Histórico' },
      { value: 'contatos', label: 'Contatos' },
    ],
    tabContent: {
      docs: 'O documento da empresa é enviado uma vez e vale para todas as obras que o exigem.',
      exigencias: 'Estas exigências vêm das obras em que a empresa está.',
      obras: 'A empresa está em 3 obras.',
      historico: '6 eventos registrados.',
      contatos: '2 contatos cadastrados.',
    },
  },
  metrics: [
    { key: 'fila', label: 'Aguardando análise', value: '12', hint: '3 esperando há mais de 2 dias' },
    { key: 'hoje', label: 'Analisados hoje', value: '8', hint: '6 aprovados • 2 reprovados' },
    { key: 'aptos', label: 'Fornecedores aptos', value: '34', hint: 'de 41 cadastrados' },
    { key: 'vencendo', label: 'Vencendo em 30 dias', value: '9', hint: 'em 7 fornecedores' },
  ],
  blocks: {
    priority: 'Fila prioritária',
    priorityAction: 'Ver fila completa',
    rows: [
      { key: 'pgr', title: 'PGR – Programa de Gerenciamento de Riscos', meta: 'Construtora Exemplo Ltda. • Residencial Mirante do Parque' },
      { key: 'rem', title: 'ASO dos funcionários • 12 arquivos', meta: 'Construtora Exemplo Ltda. • Residencial Mirante do Parque' },
    ],
    contact: 'Contato principal',
    contactItems: [
      { key: 'nome', label: 'Nome', value: 'Débora Castro' },
      { key: 'cargo', label: 'Cargo', value: 'Coordenadora administrativa' },
      { key: 'email', label: 'E-mail', value: 'debora.castro@construtoraexemplo.com.br' },
      { key: 'tel', label: 'Telefone', value: '(81) 3244-7788' },
    ],
    cardTitle: 'Cartão simples',
    cardBody: 'Cartão comum não tem sombra: tem borda de 1px. Conteúdo curto, cartão curto.',
    heightNote: 'Os dois blocos acima terminam na mesma linha, mesmo com conteúdo de tamanhos diferentes.',
  },
  table: {
    caption: 'Fornecedores de exemplo',
    columns: {
      fornecedor: 'Fornecedor',
      cnpj: 'CNPJ',
      tipo: 'Tipo',
      documentos: 'Documentos',
      situacao: 'Situação',
    },
    action: 'Abrir ficha',
    rows: [
      { id: 'f1', nome: 'Construtora Exemplo Ltda.', cnpj: '12345678000190', tipo: 'servico', docs: '5 de 9', situacao: 'comPendencia' },
      { id: 'f2', nome: 'Engemax Serviços Ltda.', cnpj: '34567890000112', tipo: 'servico', docs: '9 de 9', situacao: 'apto' },
      { id: 'f3', nome: 'Serralheria Ponto Firme ME', cnpj: '56789012000134', tipo: 'material', docs: '5 de 5', situacao: 'apto' },
      { id: 'f4', nome: 'Pinturas Litoral Ltda.', cnpj: '89012345000167', tipo: 'servico', docs: '4 de 9', situacao: 'bloqueado' },
    ],
  },
  overlays: {
    openDrawer: 'Abrir drawer',
    openModal: 'Abrir modal',
    showToast: 'Mostrar toast',
    showErrorToast: 'Mostrar toast de erro',
    drawerTitle: 'aso-marcos-lima.pdf',
    drawerSubtitle: 'ASO dos funcionários • Construtora Exemplo Ltda.',
    drawerItems: [
      { key: 'validade', label: 'Validade informada', value: '21/05/2027' },
      { key: 'enviado', label: 'Enviado em', value: '11/09/2026, 14:03' },
      { key: 'tamanho', label: 'Tamanho', value: '312 KB' },
      { key: 'envio', label: 'Envio', value: '12 arquivos' },
    ],
    drawerNote:
      'Cada arquivo é analisado sozinho e tem a sua própria validade. Documento de funcionário não entra na conta de fornecedor apto.',
    drawerCancel: 'Cancelar',
    drawerConfirm: 'Aprovar',
    modalTitle: 'Bloquear fornecedor?',
    modalDescription:
      'A Construtora Exemplo Ltda. deixa de aparecer como apta para novas contratações até regularizar a documentação.',
    modalAlert: 'O fornecedor continua acessando o portal para enviar documentos.',
    modalCancel: 'Cancelar',
    modalConfirm: 'Bloquear',
    toastSuccess: 'Documento aprovado e fornecedor avisado',
    toastError: 'Não foi possível enviar a cobrança. Tente de novo.',
    toastDone: 'aso-marcos-lima.pdf aprovado.',
    toastBlocked: 'Fornecedor bloqueado para novas contratações',
  },
  feedback: {
    infoTitle: 'O prazo não trava o fornecedor',
    info: 'Passado o prazo, os documentos não enviados continuam pendentes e entram nos relatórios de cobrança. O bloqueio é sempre decisão manual da equipe.',
    infoPlain: 'Um fornecedor só recebe as exigências das listas do mesmo tipo dele. As demais são ignoradas.',
    errorTitle: 'Este CNPJ já está cadastrado',
    error: 'Construtora Exemplo Ltda. usa o CNPJ 12.345.678/0001-90. Abra a ficha dela em vez de cadastrar de novo.',
    warningTitle: 'Obra sem lista de exigências',
    warning: 'Reserva das Águas ainda não tem lista de exigências. Os fornecedores desta obra não recebem nenhuma pendência.',
  },
  states: {
    emptyTitle: 'Nada para analisar agora',
    emptyDescription: 'Assim que um fornecedor enviar um documento, ele aparece aqui.',
    skeleton: 'Carregamento',
    empty: 'Vazio',
    error: 'Erro',
    retried: 'Nova tentativa disparada',
  },
} as const;
