/** Catálogo de estados para revisão (/_estados). */
export const estadosPage = {
  title: 'Estados para revisão',
  subtitle: (n: number) => `${n} estados com link direto. Cada um também é alcançável clicando — o caminho está descrito ao lado.`,
  caminho: 'Clicando:',
  grupos: {
    base: 'Base',
    visaoGeral: 'Visão geral',
    fila: 'Fila de análise',
    analise: 'Análise de documento',
    remessa: 'Remessa de funcionários',
    obras: 'Obras',
    obra: 'Ficha da obra',
  },
  estados: {
    componentes: ['Componentes base', 'Todos os componentes do design system e seus estados.', 'só por este link (ferramenta de revisão).'],
    naoEncontrada: ['Página não encontrada', 'Endereço que não existe.', 'digite um endereço qualquer.'],
    menuMovel: ['Menu lateral off-canvas', 'Abra em uma tela de até 1024px.', 'botão de menu no topo do conteúdo; fecha com Esc, véu ou X.'],
    vgDados: ['Com dados', 'Métricas, fila prioritária, vencimentos, últimas análises e obras em execução.', 'item "Visão geral" do menu.'],
    vgCarregando: ['Carregando', 'Esqueleto com a geometria final de cada bloco.', 'aparece por um instante ao abrir a página.'],
    vgErro: ['Erro', 'Cada bloco mostra a falha e o botão "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    vgVazio: ['Vazio', 'Cada bloco explica o que vai aparecer ali.', 'só pela URL (simulação de base vazia).'],
    filaItens: ['Com itens', '12 envios: 9 documentos e 3 remessas.', 'menu "Fila de análise".'],
    filaUrgentes: ['Filtro: urgentes', 'Faixa de filtros em "Urgentes".', 'clique em "Urgentes" na faixa de filtros.'],
    filaObra: ['Filtro: obra', 'Só os envios do Condomínio Vila Serena.', 'escolha a obra no seletor ao lado dos filtros.'],
    filaSemResultado: ['Busca sem resultado', 'Explica e oferece "Limpar filtros".', 'busque por um fornecedor sem envio na fila.'],
    filaVazia: ['Vazia', 'Nada para analisar agora.', 'aprove ou reprove todos os itens da fila.'],
    filaCarregando: ['Carregando', 'Esqueleto da faixa de filtros e da tabela.', 'aparece por um instante ao abrir a página.'],
    filaErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    anDecidindo: ['Decidindo', 'PGR da Construtora Exemplo, com a validade informada preenchida.', '"Analisar" na primeira linha da fila.'],
    anReprovando: ['Reprovando', 'Motivo e observação preenchidos com o exemplo.', '"Reprovar" no painel de decisão.'],
    anModalAprovar: ['Modal: aprovar documento', 'Validade e aviso calculados.', '"Aprovar documento" no painel de decisão.'],
    anModalReprovar: ['Modal: confirmar reprovação', 'Botão de confirmação no vermelho de perigo.', '"Confirmar reprovação" no painel de reprovação.'],
    anAprovado: ['Aprovado com toast', 'Badge vira "Aprovado", o item sai da fila e o painel mostra a decisão.', 'confirme o modal de aprovação.'],
    anFormVazio: ['Formulário vazio e erro de validade', 'Campos limpos; aprovar sem data mostra o erro no campo.', '"Limpar" no painel e depois "Aprovar documento".'],
    anRenovacao: ['Renovação', 'Nova versão do FGTS da Elétrica Aracaju; a atual continua valendo.', 'linha "Certidão de Regularidade do FGTS" na fila.'],
    anSemValidade: ['Documento sem validade', 'Contrato social da Hidro Norte: aprova sem data.', 'linha "Contrato Social consolidado" na fila.'],
    anNaoEncontrado: ['Envio não encontrado', 'Documento que não existe ou já saiu da fila.', 'só pela URL.'],
    anCarregando: ['Carregando', 'Esqueleto do visualizador e da coluna lateral.', 'aparece por um instante ao abrir a página.'],
    anErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    reTabela: ['Remessa com 8 funcionários', 'Resumo em 3 números e tabela de pessoas.', 'linha "Remessa com 8 funcionários" na fila.'],
    reDrawer: ['Drawer: pessoa em análise', 'Marcos Vinícius Lima: aprovar ou reprovar cada documento e concluir.', '"Analisar" na linha da pessoa.'],
    reDrawerConcluido: ['Drawer: pessoa já analisada', 'José Carlos de Souza: só leitura.', '"Ver" na linha da pessoa.'],
    reOutra: ['Remessa com 4 funcionários', 'Transportes Vale Verde, todos aguardando análise.', 'linha da remessa na fila.'],
    reNaoEncontrada: ['Remessa não encontrada', 'Remessa concluída ou endereço errado.', 'conclua a remessa e volte pelo histórico do navegador.'],
    reCarregando: ['Carregando', 'Esqueleto do resumo e da tabela.', 'aparece por um instante ao abrir a página.'],
    reErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    obLista: ['Lista de obras', '10 obras da integração; Reserva das Águas marcada "Sem lista de exigências".', 'menu "Obras".'],
    obVazia: ['Vazia', 'Nenhuma obra recebida da integração.', 'só pela URL (simulação de base vazia).'],
    obCarregando: ['Carregando', 'Esqueleto da tabela.', 'aparece por um instante ao abrir a página.'],
    obErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    foFornecedores: ['Aba Fornecedores', 'Residencial Mirante do Parque: 6 fornecedores, listas aplicáveis e documentos.', '"Abrir obra" na lista de obras.'],
    foExigencias: ['Aba Exigências', '3 listas, quem cada uma alcança e "Desvincular".', 'aba "Exigências".'],
    foFuncionarios: ['Aba Funcionários', 'Remessa mais recente: 8 pessoas.', 'aba "Funcionários".'],
    foPendencias: ['Aba Pendências', '5 pendências em 3 fornecedores.', 'aba "Pendências".'],
    foHistorico: ['Aba Histórico', 'Integração, vínculos, envios e vencimentos.', 'aba "Histórico".'],
    foDrawerFornecedor: ['Drawer: vincular fornecedor', 'Cimentos Nordeste preenchido; listas que se aplicam e resumo calculados.', 'botão "Vincular fornecedor" no topo.'],
    foDrawerFornecedorVazio: ['Drawer: vincular fornecedor vazio', 'Campos limpos; confirmar mostra os erros.', '"Limpar campos" no drawer e depois "Vincular fornecedor".'],
    foDrawerLista: ['Drawer: vincular lista de exigências', 'Obras públicas selecionada; as listas da obra aparecem travadas.', 'aba "Exigências" → "Vincular lista de exigências".'],
    foModalDesvincular: ['Modal: desvincular lista', 'Quem deixa de receber as exigências; botão de perigo.', 'aba "Exigências" → "Desvincular" em uma linha.'],
    foUltimaLista: ['Última lista não sai', 'Condomínio Porto Bello tem uma lista só: "Desvincular" fica desabilitado e a nota explica.', 'abra a obra Condomínio Porto Bello → "Exigências".'],
    foSemLista: ['Obra sem lista de exigências', 'Reserva das Águas: marcada no topo e aba Exigências vazia com o que fazer.', 'abra a obra Reserva das Águas.'],
    foSemFuncionarios: ['Aba Funcionários vazia', 'Centro Clínico Boa Viagem: nenhuma lista pede funcionários.', 'abra a obra Centro Clínico → "Funcionários".'],
    foSemPendencias: ['Aba Pendências vazia', 'Condomínio Vila Serena não tem pendência.', 'abra a obra Condomínio Vila Serena → "Pendências".'],
    foDrawerPessoa: ['Drawer: documentos do funcionário', 'José Carlos de Souza, da remessa mais recente.', 'aba "Funcionários" → "Ver documentos".'],
    foNaoEncontrada: ['Obra não encontrada', 'Endereço de obra que não existe.', 'só pela URL.'],
    foCarregando: ['Carregando', 'Esqueleto do topo, métricas e tabela.', 'aparece por um instante ao abrir a página.'],
    foErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
  },
} as const;
