/** Catálogo de estados para revisão (/_estados). */
export const estadosPage = {
  title: 'Estados para revisão',
  subtitle: (n: number) => `${n} estados com link direto. Cada um também é alcançável clicando — o caminho está descrito ao lado.`,
  caminho: 'Clicando:',
  grupos: {
    base: 'Base',
    visaoGeral: 'Visão geral',
    fila: 'Fila de análise',
    analise: 'Análise de documento',
    envio: 'Envio de documentos de funcionário',
    origem: 'Análise: origem e navegação',
    obras: 'Obras',
    obra: 'Ficha da obra',
    fornecedores: 'Fornecedores',
    fornecedorNovo: 'Cadastrar fornecedor',
    fornecedor: 'Ficha do fornecedor',
    listas: 'Listas de exigências',
    novaLista: 'Nova lista de exigências',
    lista: 'Configuração da lista',
    relatorios: 'Relatórios',
  },
  estados: {
    componentes: ['Componentes base', 'Todos os componentes do design system e seus estados.', 'só por este link (ferramenta de revisão).'],
    naoEncontrada: ['Página não encontrada', 'Endereço que não existe.', 'digite um endereço qualquer.'],
    menuMovel: ['Menu lateral off-canvas', 'Abra em uma tela de até 1024px.', 'botão de menu no topo do conteúdo; fecha com Esc, véu ou X.'],
    vgDados: ['Com dados', 'Métricas, fila prioritária, vencimentos, últimas análises e obras em execução.', 'item "Visão geral" do menu.'],
    vgCarregando: ['Carregando', 'Esqueleto com a geometria final de cada bloco.', 'aparece por um instante ao abrir a página.'],
    vgErro: ['Erro', 'Cada bloco mostra a falha e o botão "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    vgVazio: ['Vazio', 'Cada bloco explica o que vai aparecer ali.', 'só pela URL (simulação de base vazia).'],
    filaItens: ['Com itens', '12 itens: 9 documentos da empresa e 3 envios de documento de funcionário.', 'menu "Fila de análise".'],
    filaUrgentes: ['Filtro: urgentes', 'Faixa de filtros em "Urgentes".', 'clique em "Urgentes" na faixa de filtros.'],
    filaObra: ['Filtro: obra', 'Só os envios do Condomínio Vila Serena.', 'escolha a obra no seletor ao lado dos filtros.'],
    filaSemResultado: ['Busca sem resultado', 'Explica e oferece "Limpar filtros".', 'busque por um fornecedor sem envio na fila.'],
    filaVazia: ['Vazia', 'Nada para analisar agora.', 'aprove ou reprove todos os itens da fila.'],
    filaCarregando: ['Carregando', 'Esqueleto da faixa de filtros e da tabela.', 'aparece por um instante ao abrir a página.'],
    filaErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    anDecidindo: ['Decidindo', 'PGR da Construtora Exemplo, com a validade informada preenchida.', '"Analisar" na linha do PGR na fila.'],
    anReprovando: ['Reprovando', 'Motivo e observação preenchidos com o exemplo.', '"Reprovar" no painel de decisão.'],
    anModalAprovar: ['Modal: aprovar documento', 'Validade e aviso calculados.', '"Aprovar documento" no painel de decisão.'],
    anModalReprovar: ['Modal: confirmar reprovação', 'Botão de confirmação no vermelho de perigo.', '"Confirmar reprovação" no painel de reprovação.'],
    anAvanca: ['Aprovar e avançar', 'Ao confirmar, abre o próximo pendente da fila e mostra o toast; quando a fila acaba, volta para ela.', 'confirme o modal de aprovação.'],
    anLeitura: ['Modo leitura: aprovado', 'Certidão Negativa de Débitos Federais da Construtora: sem painel de decisão, com quem aprovou e quando.', 'ficha da Construtora → "Ver" na certidão.'],
    anLeituraReprovado: ['Modo leitura: reprovado', 'Apólice da Pinturas Litoral: quem reprovou, quando, motivo e observação.', 'ficha da Pinturas Litoral → "Ver" na apólice.'],
    anLeituraVencido: ['Modo leitura: vencido', 'FGTS da Construtora: aprovado antes, venceu em 10/09.', 'ficha da Construtora → "Ver" no FGTS.'],
    orFila: ['Origem: fila', 'Migalha "Fila de análise", contador "2 de 12" e setas ← →.', '"Analisar" em qualquer linha da fila.'],
    orFornecedor: ['Origem: ficha do fornecedor', 'Migalha "Construtora Exemplo Ltda.", contador entre os documentos dela e volta para a aba Documentos.', 'ficha da Construtora → "Analisar" no PGR.'],
    orObra: ['Origem: obra', 'Migalha com o nome da obra, percorre as pendências que têm arquivo e volta para a aba Pendências.', 'ficha do Mirante → aba Pendências → "Ver".'],
    orFimFornecedor: ['Fim da origem', 'Decidir o último pendente do fornecedor volta para a ficha com o toast dizendo que terminou.', 'pela ficha da Hidro Norte, aprove o Contrato Social.'],
    enAso: ['ASO dos funcionários da Construtora', '12 arquivos: 9 aprovados, 2 em análise e 1 reprovado; aprovar e reprovar em cada arquivo.', 'linha "ASO dos funcionários" na fila.'],
    enDrawer: ['Drawer: visualizar arquivo', 'Prévia do arquivo, validade e a decisão dele.', 'clique na linha de um arquivo.'],
    enDrawerDecidido: ['Drawer: arquivo reprovado', 'Quem reprovou, quando, motivo e observação.', 'clique no arquivo aso-wellington-duarte.pdf.'],
    enModalReprovar: ['Modal: reprovar arquivo', 'Motivo e observação preenchidos; botão de perigo. Os outros arquivos não mudam.', '"Reprovar" na linha de um arquivo em análise.'],
    enOutro: ['Ficha de entrega de EPI da Transportes Vale Verde', '4 arquivos, todos em análise.', 'linha da Transportes Vale Verde na fila.'],
    enLeitura: ['Envio em modo leitura', 'Todos os arquivos decididos: sem botões, com quem decidiu cada um.', 'ficha da Construtora → "Ver arquivos" em Ficha de entrega de EPI.'],
    enNaoEncontrado: ['Envio não encontrado', 'Envio que não existe.', 'só pela URL.'],
    enCarregando: ['Carregando', 'Esqueleto do resumo e da tabela.', 'aparece por um instante ao abrir a página.'],
    enErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    foPendenciaLeitura: ['Pendência abre em modo leitura', 'FGTS vencido da Construtora, com a obra como origem.', 'aba "Pendências" → "Ver" no FGTS.'],
    ffDocsFuncionario: ['Documentos de funcionário na ficha', 'Resumo por item ("9 de 12 aprovados • 2 em análise • 1 reprovado") e "Analisar" ou "Ver arquivos".', 'ficha da Construtora, lista Segurança do trabalho.'],
    ffSemArquivos: ['Documento de funcionário sem arquivos', 'Pinturas Litoral: "Nenhum arquivo" em cada item.', 'abra a Pinturas Litoral.'],
    clDrawerFuncionario: ['Drawer: editar documento de funcionário', 'ASO dos funcionários: validade por arquivo e aviso.', '"Editar" na linha do ASO.'],
    clDrawerNovoFuncionario: ['Drawer: novo documento de funcionário', 'Certificado NR-10 preenchido; aceita vários arquivos.', '"Adicionar documento de funcionário".'],
    anFormVazio: ['Formulário vazio e erro de validade', 'Campos limpos; aprovar sem data mostra o erro no campo.', '"Limpar" no painel e depois "Aprovar documento".'],
    anRenovacao: ['Renovação', 'Nova versão do FGTS da Elétrica Aracaju; a atual continua valendo.', 'linha "Certidão de Regularidade do FGTS" na fila.'],
    anSemValidade: ['Documento sem validade', 'Contrato social da Hidro Norte: aprova sem data.', 'linha "Contrato Social consolidado" na fila.'],
    anNaoEncontrado: ['Envio não encontrado', 'Documento que não existe ou já saiu da fila.', 'só pela URL.'],
    anCarregando: ['Carregando', 'Esqueleto do visualizador e da coluna lateral.', 'aparece por um instante ao abrir a página.'],
    anErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    obLista: ['Lista de obras', '10 obras da integração; Reserva das Águas marcada "Sem lista de exigências".', 'menu "Obras".'],
    obVazia: ['Vazia', 'Nenhuma obra recebida da integração.', 'só pela URL (simulação de base vazia).'],
    obCarregando: ['Carregando', 'Esqueleto da tabela.', 'aparece por um instante ao abrir a página.'],
    obErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    foFornecedores: ['Aba Fornecedores', 'Residencial Mirante do Parque: 6 fornecedores, listas aplicáveis e documentos.', '"Abrir obra" na lista de obras.'],
    foExigencias: ['Aba Exigências', '3 listas, quem cada uma alcança e "Desvincular".', 'aba "Exigências".'],
    foPendencias: ['Aba Pendências', '6 pendências em 3 fornecedores, inclusive documentos de funcionário.', 'aba "Pendências".'],
    foHistorico: ['Aba Histórico', 'Integração, vínculos, envios e vencimentos.', 'aba "Histórico".'],
    foDrawerFornecedor: ['Drawer: vincular fornecedor', 'Cimentos Nordeste preenchido; listas que se aplicam e resumo calculados.', 'botão "Vincular fornecedor" no topo.'],
    foDrawerFornecedorVazio: ['Drawer: vincular fornecedor vazio', 'Campos limpos; confirmar mostra os erros.', '"Limpar campos" no drawer e depois "Vincular fornecedor".'],
    foDrawerLista: ['Drawer: vincular lista de exigências', 'Obras públicas selecionada; as listas da obra aparecem travadas.', 'aba "Exigências" → "Vincular lista de exigências".'],
    foModalDesvincular: ['Modal: desvincular lista', 'Quem deixa de receber as exigências; botão de perigo.', 'aba "Exigências" → "Desvincular" em uma linha.'],
    foUltimaLista: ['Última lista não sai', 'Condomínio Porto Bello tem uma lista só: "Desvincular" fica desabilitado e a nota explica.', 'abra a obra Condomínio Porto Bello → "Exigências".'],
    foSemLista: ['Obra sem lista de exigências', 'Reserva das Águas: marcada no topo e aba Exigências vazia com o que fazer.', 'abra a obra Reserva das Águas.'],
    foSemPendencias: ['Aba Pendências vazia', 'Condomínio Vila Serena não tem pendência.', 'abra a obra Condomínio Vila Serena → "Pendências".'],
    foNaoEncontrada: ['Obra não encontrada', 'Endereço de obra que não existe.', 'só pela URL.'],
    foCarregando: ['Carregando', 'Esqueleto do topo, métricas e tabela.', 'aparece por um instante ao abrir a página.'],
    foErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    flLista: ['Lista', '41 fornecedores, com situação, tipo, documentos e listas aplicáveis.', 'menu "Fornecedores".'],
    flSituacao: ['Filtro: com pendência', 'Faixa de situação em "Com pendência".', 'clique em "Com pendência" na faixa.'],
    flTipo: ['Filtro: material', 'Só fornecedores de material.', 'escolha "Material" no seletor de tipo.'],
    flBuscaCnpj: ['Busca por CNPJ', 'A busca aceita CNPJ com ou sem pontuação.', 'digite o começo do CNPJ na busca.'],
    flAguardando: ['Aguardando 1º acesso', 'Cerâmica Vale do Ipojuca: badge e "Reenviar acesso" no botão da linha.', 'busque por "Cerâmica".'],
    flModalReenviar: ['Modal: reenviar primeiro acesso', 'E-mail editável e data do convite anterior.', '"Reenviar acesso" na linha da Cerâmica.'],
    flSemResultado: ['Busca sem resultado', 'Explica e oferece "Limpar filtros".', 'busque por um nome que não existe.'],
    flVazia: ['Vazia', 'Nenhum fornecedor; convida a cadastrar.', 'só pela URL (simulação de base vazia).'],
    flCarregando: ['Carregando', 'Esqueleto dos filtros e da tabela.', 'aparece por um instante ao abrir a página.'],
    flErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    fnPreenchido: ['Preenchido', 'Revest Nordeste nos quatro blocos, com a obra Mirante e as listas que vão se aplicar.', '"Cadastrar fornecedor" na lista de fornecedores.'],
    fnVazio: ['Vazio', 'Formulário limpo.', '"Limpar" no topo do formulário.'],
    fnErros: ['Erros de validação', 'Campos obrigatórios marcados e alerta no topo.', '"Limpar" e depois "Cadastrar fornecedor".'],
    fnDuplicado: ['CNPJ já cadastrado', 'Erro no campo e alerta no topo com link para a ficha da Construtora Exemplo.', 'digite 12.345.678/0001-90 no CNPJ.'],
    fnCadastrado: ['Cadastrado', 'Volta para a lista com a empresa no topo, marcada "Aguardando 1º acesso".', '"Cadastrar fornecedor" com o formulário preenchido.'],
    ffDocumentos: ['Aba Documentos', 'Construtora Exemplo: documentos da empresa por lista de exigências.', 'clique na linha da Construtora Exemplo.'],
    ffExigencias: ['Aba Exigências', 'Listas aplicáveis e a lista ignorada por tipo.', 'aba "Exigências".'],
    ffObras: ['Aba Obras', '3 obras com serviço contratado e período.', 'aba "Obras".'],
    ffHistorico: ['Aba Histórico', 'Envios, decisões e vínculos.', 'aba "Histórico".'],
    ffContatos: ['Aba Contatos', 'Contato principal, segurança do trabalho e acesso ao portal.', 'aba "Contatos".'],
    ffModalBloquear: ['Modal: bloquear fornecedor', 'Botão de perigo; ao confirmar, a situação vira "Bloqueado".', '"Bloquear fornecedor" no topo.'],
    ffBloqueado: ['Fornecedor bloqueado', 'Pinturas Litoral: "Desbloquear" no lugar de "Bloquear".', 'abra a Pinturas Litoral.'],
    ffModalReenviar: ['Modal: reenviar acesso na ficha', 'Cerâmica Vale do Ipojuca, aguardando 1º acesso.', '"Reenviar acesso" no topo da ficha ou na aba Contatos.'],
    ffNaoEncontrado: ['Não encontrado', 'Fornecedor que não existe.', 'só pela URL.'],
    ffCarregando: ['Carregando', 'Esqueleto do topo, das abas e da tabela.', 'aparece por um instante ao abrir a página.'],
    ffErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    liLista: ['Listas', 'As quatro listas com tipo, composição, obras e alcance.', 'menu "Exigências".'],
    liVazia: ['Vazia', 'Nenhuma lista; convida a criar.', 'só pela URL (simulação de base vazia).'],
    liCarregando: ['Carregando', 'Esqueleto dos cartões.', 'aparece por um instante ao abrir a página.'],
    liErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    nlServico: ['Tipo serviço', 'Preenchida com os 8 itens de Segurança do trabalho, inclusive os documentos de funcionário.', '"Nova lista de exigências" nas listas.'],
    nlMaterial: ['Tipo material', 'O alcance nas obras passa a contar fornecedores de material.', 'escolha "Material" no tipo de lista.'],
    nlVazio: ['Vazio e erros', 'Formulário limpo; criar sem nome e sem itens mostra os erros.', '"Limpar" e depois "Criar lista".'],
    nlDrawers: ['Drawers dentro da nova lista', 'Documento da empresa e documento de funcionário entram no rascunho.', 'os dois botões "Adicionar" no bloco 2.'],
    clItens: ['Itens e obras', 'Segurança do trabalho: 8 itens (4 da empresa, 4 de funcionário) e as 3 obras em que vale.', '"Configurar" na lista Segurança do trabalho.'],
    clDrawerDocumento: ['Drawer: novo documento da empresa', 'Certidão Negativa Estadual preenchida; impacto calculado.', '"Adicionar documento da empresa".'],
    clDrawerEditarDocumento: ['Drawer: editar documento', 'O PGR com os dados atuais.', '"Editar" na linha do PGR.'],
    clDrawerObras: ['Drawer: vincular a obras', 'Reserva das Águas e Centro Clínico selecionadas; as atuais travadas.', '"Vincular a obras".'],
    clModalRemover: ['Modal: remover a lista de uma obra', 'Quem deixa de receber as exigências; botão de perigo.', '"Remover desta obra" em uma das obras.'],
    clUnica: ['Única lista da obra', 'Habilitação — serviço é a única do Condomínio Porto Bello: não sai.', 'Habilitação — serviço → bloco de obras.'],
    clMaterial: ['Lista de material', 'Habilitação — material, com 5 documentos da empresa.', '"Configurar" na Habilitação — material.'],
    clNaoEncontrada: ['Não encontrada', 'Lista que não existe.', 'só pela URL.'],
    clCarregando: ['Carregando', 'Esqueleto do topo e da tabela.', 'aparece por um instante ao abrir a página.'],
    clErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
    rlTrinta: ['Últimos 30 dias', 'Pendências por obra, tempo médio por lista e vencimentos.', 'menu "Relatórios".'],
    rlNoventa: ['Últimos 90 dias', 'O tempo médio muda com o período.', 'escolha "Últimos 90 dias" no seletor.'],
    rlAno: ['Este ano', 'Obras públicas também passa da meta.', 'escolha "Este ano" no seletor.'],
    rlExportar: ['Exportar', 'Baixa um CSV com as três seções.', '"Exportar" no topo.'],
    rlVazio: ['Vazio', 'Cada seção explica o que aparece ali.', 'só pela URL (simulação de base vazia).'],
    rlCarregando: ['Carregando', 'Esqueleto das três seções.', 'aparece por um instante ao abrir a página.'],
    rlErro: ['Erro', 'Falha ao carregar, com "Tentar de novo".', 'só pela URL (simulação de falha da API).'],
  },
} as const;
