/** Fila de análise (/fila). */
export const filaPage = {
  title: 'Fila de análise',
  subtitle: 'Documentos e envios de arquivos esperando decisão',
  searchLabel: 'Buscar na fila',
  searchPlaceholder: 'Buscar por fornecedor, obra ou documento',
  filtrosLabel: 'Filtrar por tipo de envio',
  filtros: {
    todos: 'Todos',
    empresa: 'Documentos da empresa',
    funcionario: 'Documentos de funcionário',
    urgentes: 'Urgentes',
  },
  obraLabel: 'Filtrar por obra',
  todasObras: 'Todas as obras',
  obraOpcao: (obra: string, n: number) => `${obra} (${n})`,
  caption: 'Itens esperando análise',
  colunas: {
    fornecedor: 'Fornecedor',
    item: 'Item',
    obra: 'Obra',
    lista: 'Lista de exigências',
    enviadoEm: 'Enviado em',
    espera: 'Espera',
    prioridade: 'Prioridade',
  },
  renovacao: 'nova versão',
  arquivos: (n: number) => (n === 1 ? '1 arquivo' : `${n} arquivos`),
  acao: 'Analisar',
  vaziaTitle: 'Nada para analisar agora',
  vaziaDescription:
    'Assim que um fornecedor enviar um documento da empresa ou arquivos de um documento de funcionário, o envio aparece aqui. Enquanto isso, acompanhe os vencimentos na visão geral.',
  vaziaAction: 'Ir para a visão geral',
  semResultadoTitle: 'Nenhum item com estes filtros',
  semResultadoDescription: 'Troque o filtro, escolha outra obra ou apague a busca para ver a fila inteira.',
  limparFiltros: 'Limpar filtros',
} as const;
