/** Cadastrar fornecedor (/fornecedores/novo). */
export const fornecedorNovoPage = {
  voltar: 'Fornecedores',
  title: 'Cadastrar fornecedor',
  subtitle: 'A empresa recebe um convite para o portal e passa a ver as exigências das obras em que estiver.',
  limpar: 'Limpar',
  cancelar: 'Cancelar',
  salvar: 'Cadastrar fornecedor',
  alertaCnpjTitle: 'Este CNPJ já está cadastrado',
  alertaCnpj: (razao: string) => `${razao} já usa este CNPJ. Abra a ficha dela em vez de cadastrar de novo.`,
  abrirFicha: 'Abrir ficha',
  alertaErrosTitle: 'Revise os campos marcados',
  alertaErros: 'Alguns campos obrigatórios estão vazios ou com formato inválido.',
  identificacao: {
    title: '1. Identificação',
    cnpj: 'CNPJ',
    cnpjPlaceholder: '00.000.000/0000-00',
    cnpjErro: 'CNPJ inválido. Confira os 14 dígitos.',
    cnpjDuplicado: (razao: string) => `Este CNPJ já está cadastrado: ${razao}`,
    razao: 'Razão social',
    razaoErro: 'Informe a razão social.',
    fantasia: 'Nome fantasia (opcional)',
  },
  tipo: {
    title: '2. Tipo de fornecedor',
    servico: 'Serviço',
    servicoDesc: 'Executa serviço na obra e coloca pessoas em campo',
    material: 'Material',
    materialDesc: 'Fornece material e não executa serviço',
    nota: 'Só as listas de exigências do mesmo tipo se aplicam a este fornecedor.',
  },
  contato: {
    title: '3. Contato e primeiro acesso',
    nome: 'Nome do contato',
    nomeErro: 'Informe quem é o contato.',
    cargo: 'Cargo (opcional)',
    email: 'E-mail',
    emailHint: 'O convite de primeiro acesso vai para este e-mail.',
    emailErro: 'Informe um e-mail válido.',
    telefone: 'Telefone (opcional)',
    telefonePlaceholder: '(81) 99999-9999',
    convite: 'Enviar o convite de primeiro acesso agora',
    conviteHint: 'Até entrar no portal, o fornecedor aparece como "aguardando 1º acesso".',
  },
  obra: {
    title: '4. Obra (opcional)',
    description: 'Vincule já a obra em que a empresa vai trabalhar. Dá para fazer isso depois, na ficha da obra.',
    obra: 'Obra',
    nenhuma: 'Nenhuma por enquanto',
    opcao: (obra: string, codigo: string) => `${obra} • ${codigo}`,
    servico: 'Serviço contratado',
    servicoPlaceholder: 'Ex.: Revestimento de fachada',
    servicoErro: 'Diga o que foi contratado nesta obra.',
    listas: 'Listas de exigências desta obra',
    aplica: 'Vai se aplicar',
    naoAplica: (tipo: string) => `Não se aplica — tipo ${tipo}`,
    semListas: 'Esta obra ainda não tem lista de exigências.',
  },
} as const;
