/** Cadastrar fornecedor (/fornecedores/novo). */
export const fornecedorNovoPage = {
  voltar: 'Fornecedores',
  title: 'Cadastrar fornecedor',
  subtitle: 'A empresa passa a ver as exigências das obras em que estiver, conforme o tipo de fornecimento.',
  limpar: 'Limpar',
  cancelar: 'Cancelar',
  salvar: 'Cadastrar fornecedor',
  salvando: 'Cadastrando…',
  alertaCnpjTitle: 'Este CNPJ já está cadastrado',
  alertaCnpj: (razao: string) => `${razao} já usa este CNPJ. Abra a ficha dela em vez de cadastrar de novo.`,
  abrirFicha: 'Abrir ficha',
  alertaErrosTitle: 'Revise os campos marcados',
  alertaErros: 'Alguns campos obrigatórios estão vazios ou com formato inválido.',
  alertaApiTitle: 'Não foi possível cadastrar',
  identificacao: {
    title: '1. Identificação',
    cnpj: 'CNPJ',
    cnpjPlaceholder: '00.000.000/0000-00',
    cnpjErro: 'CNPJ inválido. Confira os 14 dígitos.',
    cnpjDuplicado: (razao: string) => `Este CNPJ já está cadastrado: ${razao}`,
    razao: 'Razão social',
    razaoErro: 'Informe a razão social, com pelo menos 2 letras.',
    telefone: 'Telefone da empresa',
    telefonePlaceholder: '(81) 3333-4444',
    telefoneErro: 'Telefone inválido. Informe DDD e número, com 10 ou 11 dígitos.',
    email: 'E-mail da empresa',
    emailErro: 'Informe um e-mail válido.',
  },
  tipo: {
    title: '2. Tipo de fornecedor',
    servico: 'Serviço',
    servicoDesc: 'Executa serviço na obra e coloca pessoas em campo',
    material: 'Material',
    materialDesc: 'Fornece material e não executa serviço',
    nota: 'Marque um ou os dois. Só as listas de exigências de um tipo que a empresa fornece se aplicam a ela.',
    erro: 'Escolha pelo menos um tipo.',
  },
  obra: {
    title: '3. Obra (opcional)',
    description: 'Vincule já a obra em que a empresa vai trabalhar. Dá para fazer isso depois, na ficha da obra.',
    indisponivel: 'Indisponível: a API ainda não tem endpoint para vincular fornecedor a obra. O vínculo continua sendo feito fora deste sistema.',
    obra: 'Obra',
    nenhuma: 'Nenhuma por enquanto',
    opcao: (obra: string, codigo?: string) => (codigo ? `${obra} • ${codigo}` : obra),
    servico: 'Serviço contratado',
    servicoPlaceholder: 'Ex.: Revestimento de fachada',
    servicoErro: 'Diga o que foi contratado nesta obra.',
    listas: 'Listas de exigências desta obra',
    aplica: 'Vai se aplicar',
    naoAplica: (tipo: string) => `Não se aplica — tipo ${tipo}`,
    semListas: 'Esta obra ainda não tem lista de exigências.',
  },
  /** Campo recusado pela API num 400. */
  recusado: {
    razaoSocial: 'A API recusou a razão social. Use de 2 a 255 caracteres.',
    cnpj: 'A API recusou o CNPJ. Confira os 14 dígitos.',
    telefone: 'A API recusou o telefone. Informe DDD e número.',
    email: 'A API recusou o e-mail. Confira o endereço.',
    tipos: 'A API recusou o tipo. Escolha pelo menos um.',
  },
} as const;
